stages:
  preprocess:
    cmd: python src/pipeline/data_preprocessing.py
    deps:
      - data/raw/experiment_dataset.csv
      - src/pipeline/data_preprocessing.py
    outs:
      - data/processed/experiment_dataset_cleaned.csv

  inference:
    cmd: python main.py
    deps:
      - data/processed/experiment_dataset_cleaned.csv
      - main.py
      - src
    params:
      - llm.model_name
      - llm.batch_size
      - llm.summary_temperature
      - llm.reply_temperature

  select_best_model:
    cmd: python src/pipeline/select_best_model.py
    deps:
      - src/pipeline/select_best_model.py
      - mlflow.db
    outs:
      - configs/best_model_config.json